# SQLite version 3.x
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: empower_me_dev

test:
  <<: *default
  database: empower_me_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
